# NexT Theme Configuration

scheme: Gemini

avatar:
  url: https://avatars.githubusercontent.com/u/21107549?v=4
  rounded: true
  rotated: false

sidebar:
  position: right
  display: post
  padding: 18
  offset: 12

menu:
  home: / || fas fa-home
  about: /about/ || fas fa-user
  tags: /tags/ || fas fa-tags
  categories: /categories/ || fas fa-th
  archives: /archives/ || fas fa-archive
  schedule: /schedule/ || fas fa-calendar

menu_settings:
  icons: true
  hidden: false
  badges: true

darkmode: false

font:
  enable: true
  host: https://fonts.loli.net
  global:
    family: Monda
  title:
    family: Roboto Slab
  headings:
    family: Roboto Slab
  posts:
    family: Noto Serif SC
  codes:
    family: Xcode

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true

reward_settings:
  enable: true
  animation: true

reward:
  wechatpay: /images/wechatpay.png
  alipay: /images/alipay.png

social:
  GitHub: https://github.com/sunbos || fab fa-github
  QQ: http://wpa.qq.com/msgrd?v=3&uin=1443584939&site=qq&menu=yes || fab fa-qq
  E-Mail: mailto:1443584939@qq.com || fa fa-envelope

motion:
  enable: true

copycode:
  enable: true
  show_result: true
  style: mac

bookmark:
  enable: true
  color: "#222"
  save: "auto"

fancybox: true
lazyload: true
pangu: true

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: true

local_search:
  enable: true
  trigger: auto

waline:
  enable: true
  serverURL: https://imnerd-api-lemon.vercel.app
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊!
  avatar: mm
  visitor: true

custom_file_path:
  variables: source/_data/variables.styl
  style: source/_data/styles.styl
  bodyEnd: source/_data/body-end.njk
  footer: source/_data/footer.njk
  sidebar: source/_data/sidebar.njk
  postBodyEnd: source/_data/post-body-end.njk
